# AWS Playbook
---

- name: Train model on AWS SageMaker
  hosts: local
  gather_facts: False
  tasks:

  - name: Assume FullSageMaker role
    sts_assume_role:
      role_arn: "{{ AWS_ROLE_ARN }}"
      role_session_name: "{{ AWS_ROLE_NAME }}"
    environment:
      AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY }}"
      AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_KEY }}"
    register: aws_role

  - name: Get AWS ECR login
    command: "aws ecr get-login-password --region {{ AWS_REGION }}"
    environment:
      AWS_ACCESS_KEY_ID: "{{ aws_role.sts_creds.access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_role.sts_creds.secret_key }}"
      AWS_SECURITY_TOKEN: "{{ aws_role.sts_creds.session_token }}"
    register: ecr_login

  - name: Login to AWS ECR managed repository
    command: "docker login --username AWS --password {{ ecr_login.stdout }} 763104351884.dkr.ecr.{{ AWS_REGION }}.amazonaws.com"

  - name: Pull image from AWS ECR managed repository
    command: "docker pull 763104351884.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/tensorflow-training:2.3.0-cpu-py37-ubuntu18.04"

  - name: Build docker image
    command: "docker build . -t demo-sagemaker-image"

  - name: List s3 buckets
    aws_s3_bucket_info:
      aws_access_key: "{{ aws_role.sts_creds.access_key }}"
      aws_secret_key: "{{ aws_role.sts_creds.secret_key }}"
      security_token: "{{ aws_role.sts_creds.session_token }}"
    register: s3_buckets

  - name: Login to AWS ECR own repository
    command: "docker login --username AWS --password {{ ecr_login.stdout }} 625399435531.dkr.ecr.{{ AWS_REGION }}.amazonaws.com"

  - name: Tag docker image to AWS ECR own repository
    command: "docker tag demo-sagemaker-image:latest 625399435531.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/demo-sagemaker:latest"

  - name: Push docker image to AWS ECR own repository
    command: "docker push 625399435531.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/demo-sagemaker:latest"

  - name: Run SageMaker training job
    run_sagemaker:
      aws_access_key: "{{ aws_role.sts_creds.access_key }}"
      aws_secret_key: "{{ aws_role.sts_creds.secret_key }}"
      security_token: "{{ aws_role.sts_creds.session_token }}"
      training_image: "625399435531.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/demo-sagemaker:latest"
      s3_output_path: "s3://{{ s3_buckets.buckets[0].name }}"
    register: sagemaker_response

  - name: Print training job
    debug:
      msg: "{{ sagemaker_response }}"

  - name: Wait for job to complete...
    get_job_status:
      aws_access_key: "{{ aws_role.sts_creds.access_key }}"
      aws_secret_key: "{{ aws_role.sts_creds.secret_key }}"
      security_token: "{{ aws_role.sts_creds.session_token }}"
      training_job_arn: "{{ sagemaker_response.TrainingJobArn }}"
      wait_between_tries: "{{ WAIT_BETWEEN_TRIES }}"
      duration_threshold: "{{ DURATION_THRESHOLD }}"
    register: training_job_status

  - name: Training job final status
    debug:
      msg: "{{ training_job_status }}"

  - name: Retrieve trained model from S3
    aws_s3:
      aws_access_key: "{{ aws_role.sts_creds.access_key }}"
      aws_secret_key: "{{ aws_role.sts_creds.secret_key }}"
      security_token: "{{ aws_role.sts_creds.session_token }}"
      bucket: "demo-sagemaker-artifacts"
      object: "/{{ sagemaker_response.JobName }}/output/model.tar.gz"
      dest: "/Users/thomaspesneau/Documents/Projects/demo-ansible-sagemaker/models/model.tar.gz"
      mode: "get"
