# AWS Playbook
---

- name: Train model on AWS SageMaker
  hosts: local
  gather_facts: False
  tasks:
  - name: Assume FullSageMaker role
    sts_assume_role:
      role_arn: "{{ AWS_ROLE_ARN }}"
      role_session_name: "{{ AWS_ROLE_NAME }}"
    environment:
      AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY }}"
      AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_KEY }}"
    register: aws_role
  - debug: msg="{{ aws_role }}"
  - name: Amazon ECR authentication
    command: "aws ecr get-login-password --region {{ AWS_REGION }}"
    environment:
      AWS_ACCESS_KEY_ID: "{{ aws_role.sts_creds.access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_role.sts_creds.secret_key }}"
      AWS_SECURITY_TOKEN: "{{ aws_role.sts_creds.session_token }}"
    register: ecr_login
  - debug: msg="{{ ecr_login }}"
  - name: Docker login
    command: "docker login --username AWS --password {{ ecr_login.stdout }} 763104351884.dkr.ecr.{{ AWS_REGION }}.amazonaws.com"
  - name: Pull image from ECR
    command: "docker pull 763104351884.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/tensorflow-training:2.3.0-cpu-py37-ubuntu18.04"
  - name: Build docker image
    command: "docker build . -t demo-sagemaker-image"
  - name: list s3 buckets # Just for testing the read writes where granted
    aws_s3_bucket_info:
      aws_access_key: "{{ aws_role.sts_creds.access_key }}"
      aws_secret_key: "{{ aws_role.sts_creds.secret_key }}"
      security_token: "{{ aws_role.sts_creds.session_token }}"
    register: s3_buckets
  - debug: msg="{{ s3_buckets }}" # Should return testfullsagemakerrole bucket info
  - name: Push docker image to AWS ECR (TODO)
    shell: echo "Send docker image to AWS ECR"
  - name: Build sagemaker training instance (TODO)
    shell: echo "Build sagemaker training instance"
  - name: Run sagemaker training instance from docker image (TODO)
    shell: echo "Run sagemaker training instance"


